# -*- coding: utf-8 -*-
"""
Plot Fig. 5b | Task-wise ΔMacro-F1 heatmap for framework-level ablations.

Input:
    Excel generated by result5_framework_ablation_summary_v4.py
    Sheet: Fig5b_delta_heatmap_long

Output:
    Fig5b_delta_macro_f1_heatmap.png
    Fig5b_delta_macro_f1_heatmap.pdf
    Fig5b_delta_macro_f1_heatmap.svg

Figure design:
    - Rows: framework-level ablations
    - Columns: t1–t5
    - Cell value: Δ Macro-F1 = ablation variant − Proposed framework
    - Negative values indicate performance loss after removing a component.

Updated style:
    1. Fig2C-like serif font style.
    2. Remove left-side ablation color bars.
    3. Use unified ablation names.
    4. Y-axis labels are wrapped as "w/o\\nComponent".
    5. X-axis only shows t1–t5.
    6. Colorbar only displays -0.20 to 0.00.
"""

from pathlib import Path
import re

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap, Normalize


# ============================================================
# 1. 路径配置：主要修改这里
# ============================================================

EXCEL_PATH = Path(
    r"xx_path"
)

SHEET_NAME = "Fig5b_delta_heatmap_long"

OUTPUT_DIR = EXCEL_PATH.parent
OUTPUT_BASENAME = "Fig5b_delta_macro_f1_heatmap"


# ============================================================
# 2. 任务与实验显示配置
# ============================================================

TASK_ORDER = ["t1", "t2", "t3", "t4", "t5"]

TASK_DISPLAY_NAME = {
    "t1": "t1",
    "t2": "t2",
    "t3": "t3",
    "t4": "t4",
    "t5": "t5",
}

# y 轴顺序倒转：
# 从上到下为 T6-Ctx → αβ-Routing → β-Experts → 9P-Prior
DISPLAY_ORDER = [
    "w/o T6-Ctx",
    "w/o αβ-Routing",
    "w/o β-Experts",
    "w/o 9P-Prior",
]

EXPERIMENT_DISPLAY_NAME = {
    "E1": "w/o T6-Ctx",
    "E2": "w/o αβ-Routing",
    "E3": "w/o β-Experts",
    "E4": "w/o 9P-Prior",
    "S6": "w/o 9P-Prior",
}

EXPERIMENT_FULL_NAME = {
    "E1": "w/o T6 disease-context module",
    "E2": "w/o dual-trunk routing",
    "E3": "w/o Beta expert decomposition",
    "E4": "w/o nine-panel prior-guided chain",
    "S6": "w/o nine-panel prior-guided chain",
}


# ============================================================
# 3. Heatmap 色卡
# ============================================================

# 只用于展示性能损失：
# -0.20 为深红，0 为白色。
# 由于 Fig5b 表达的是 loss，因此不使用蓝色正向区间。
HEATMAP_CMAP = LinearSegmentedColormap.from_list(
    "macro_f1_loss_cmap",
    [
        "#B2182B",  # deepest red
        "#D6604D",
        "#F4A582",
        "#FDDBC7",# zero
    ]
)


# ============================================================
# 4. 绘图参数：统一 Fig2C / Fig1C 风格
# ============================================================

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "DejaVu Serif"],
    "font.size": 10.5,
    "axes.titlesize": 11.5,
    "axes.labelsize": 11,
    "xtick.labelsize": 9.5,
    "ytick.labelsize": 9.5,
    "axes.linewidth": 1.0,
    "xtick.major.width": 1.0,
    "ytick.major.width": 1.0,
    "xtick.major.size": 3.5,
    "ytick.major.size": 3.5,
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
    "svg.fonttype": "none",
})

FIGSIZE = (6.8, 3.35)
DPI = 600


# ============================================================
# 5. 工具函数
# ============================================================

def normalize_text(x):
    if pd.isna(x):
        return ""
    return str(x).strip()


def parse_numeric(x):
    """
    支持：
    - float / int
    - '0.1234'
    - '-0.1234'
    - '0.1234 ± 0.0123'
    """
    if pd.isna(x):
        return np.nan

    if isinstance(x, (int, float, np.number)):
        return float(x)

    s = str(x).strip().replace("−", "-")
    if not s:
        return np.nan

    m = re.search(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", s)
    if not m:
        return np.nan

    return float(m.group(0))


def find_col(df, candidates, required=True):
    """
    在 df 中按候选名寻找列。
    兼容空格、大小写和不同破折号。
    """
    lower_map = {str(c).strip().lower(): c for c in df.columns}

    for cand in candidates:
        key = str(cand).strip().lower()
        if key in lower_map:
            return lower_map[key]

    norm_candidates = [
        re.sub(
            r"\s+",
            "",
            str(c).lower().replace("–", "-").replace("—", "-")
        )
        for c in candidates
    ]

    for col in df.columns:
        norm_col = re.sub(
            r"\s+",
            "",
            str(col).lower().replace("–", "-").replace("—", "-")
        )
        if norm_col in norm_candidates:
            return col

    if required:
        raise ValueError(
            f"找不到列：{candidates}\n"
            f"当前列：{list(df.columns)}"
        )

    return None


def infer_display_name(experiment, model_variant):
    """
    将 Excel 中的 Experiment / Model variant 统一映射到图中显示名称。
    """
    experiment = normalize_text(experiment)
    model_variant = normalize_text(model_variant)

    if experiment in EXPERIMENT_DISPLAY_NAME:
        return EXPERIMENT_DISPLAY_NAME[experiment]

    lower = model_variant.lower()

    if "t6" in lower and ("context" in lower or "ctx" in lower):
        return "w/o T6-Ctx"

    if (
        "dual" in lower
        or "routing" in lower
        or "single-alpha" in lower
        or "single alpha" in lower
    ):
        return "w/o αβ-Routing"

    if "beta" in lower and ("expert" in lower or "shared" in lower):
        return "w/o β-Experts"

    if "prior" in lower or "nine-panel" in lower or "9p" in lower:
        return "w/o 9P-Prior"

    return model_variant


def format_ablation_label(name):
    """
    y 轴标签换行：
    w/o 9P-Prior -> w/o\\n9P-Prior
    """
    name = str(name)
    if name.startswith("w/o "):
        return name.replace("w/o ", "w/o\n", 1)
    return name


def load_fig5b_data(excel_path, sheet_name):
    df = pd.read_excel(excel_path, sheet_name=sheet_name)

    exp_col = find_col(df, ["Experiment"], required=False)
    variant_col = find_col(df, ["Model variant", "model_variant"], required=False)
    task_col = find_col(df, ["Task", "task"], required=True)

    delta_col = find_col(
        df,
        [
            "Delta Macro-F1 mean",
            "Δ Macro-F1 mean",
            "Delta Macro-F1",
            "Δ Macro-F1",
        ],
        required=True,
    )

    sd_col = find_col(
        df,
        [
            "Delta Macro-F1 SD",
            "Δ Macro-F1 SD",
        ],
        required=False,
    )

    rows = []

    for _, row in df.iterrows():
        exp = normalize_text(row[exp_col]) if exp_col else ""
        variant = normalize_text(row[variant_col]) if variant_col else ""
        task = normalize_text(row[task_col])

        if task not in TASK_ORDER:
            continue

        display_name = infer_display_name(exp, variant)

        if display_name not in DISPLAY_ORDER:
            continue

        rows.append({
            "Experiment": exp,
            "Model variant": variant,
            "Display name": display_name,
            "Task": task,
            "Delta Macro-F1 mean": parse_numeric(row[delta_col]),
            "Delta Macro-F1 SD": parse_numeric(row[sd_col]) if sd_col else np.nan,
        })

    out = pd.DataFrame(rows)

    if out.empty:
        raise ValueError(
            "Fig5b 数据为空。请检查 sheet、列名或 Experiment / Model variant 命名。"
        )

    out["Display name"] = pd.Categorical(
        out["Display name"],
        categories=DISPLAY_ORDER,
        ordered=True,
    )

    out["Task"] = pd.Categorical(
        out["Task"],
        categories=TASK_ORDER,
        ordered=True,
    )

    out = (
        out.sort_values(["Display name", "Task"])
        .drop_duplicates(subset=["Display name", "Task"], keep="first")
        .reset_index(drop=True)
    )

    return out


def build_matrix(df):
    value_mat = (
        df.pivot(
            index="Display name",
            columns="Task",
            values="Delta Macro-F1 mean",
        )
        .reindex(index=DISPLAY_ORDER, columns=TASK_ORDER)
    )

    sd_mat = (
        df.pivot(
            index="Display name",
            columns="Task",
            values="Delta Macro-F1 SD",
        )
        .reindex(index=DISPLAY_ORDER, columns=TASK_ORDER)
    )

    return value_mat, sd_mat


def get_norm():
    """
    固定 colorbar 范围为 -0.20 到 0.00。
    """
    return Normalize(vmin=-0.20, vmax=0.00)


# ============================================================
# 6. 绘图主函数
# ============================================================

def plot_heatmap(value_mat, sd_mat):
    values = value_mat.to_numpy(dtype=float)

    fig, ax = plt.subplots(figsize=FIGSIZE)

    norm = get_norm()
    im = ax.imshow(
        values,
        cmap=HEATMAP_CMAP,
        norm=norm,
        aspect="auto",
        interpolation="nearest",
    )

    # -------------------------
    # x 轴：只显示 t1–t5
    # -------------------------
    ax.set_xticks(np.arange(len(TASK_ORDER)))
    ax.set_xticklabels(
        [TASK_DISPLAY_NAME[t] for t in TASK_ORDER],
        fontsize=10.5,
        fontweight="normal",
    )

    # -------------------------
    # y 轴：统一名称 + w/o 换行
    # -------------------------
    ax.set_yticks(np.arange(len(value_mat.index)))
    ax.set_yticklabels(
        [format_ablation_label(x) for x in value_mat.index.tolist()],
        fontsize=10.5,
        linespacing=1.05,
    )

    ax.tick_params(
        axis="x",
        bottom=False,
        top=False,
        labelbottom=True,
        pad=-1,
    )

    ax.tick_params(
        axis="y",
        left=False,
        right=False,
        labelleft=True,
        pad=-1,
    )

    # -------------------------
    # 白色分隔线
    # -------------------------
    ax.set_xticks(np.arange(-0.5, len(TASK_ORDER), 1), minor=True)
    ax.set_yticks(np.arange(-0.5, len(value_mat.index), 1), minor=True)

    ax.grid(
        which="minor",
        color="white",
        linestyle="-",
        linewidth=1.6,
    )

    ax.tick_params(
        which="minor",
        bottom=False,
        left=False,
    )

    # -------------------------
    # 单元格数值标注
    # -------------------------
    for i in range(values.shape[0]):
        for j in range(values.shape[1]):
            val = values[i, j]

            if not np.isfinite(val):
                txt = "NA"
                txt_color = "black"
                weight = "normal"
            else:
                txt = f"{val:.3f}"
                txt_color = "black"

                # 仅加粗每一行中损失最大的任务
                row_min = np.nanmin(values[i, :])
                weight = "bold" if np.isclose(val, row_min, atol=1e-8) else "normal"

            ax.text(
                j,
                i,
                txt,
                ha="center",
                va="center",
                fontsize=10,
                color=txt_color,
                fontweight=weight,
            )

    # -------------------------
    # colorbar：只展示 -0.20 到 0.00
    # -------------------------
    cbar = fig.colorbar(
        im,
        ax=ax,
        fraction=0.040,
        pad=0.030,
        ticks=[-0.20, -0.15, -0.10, -0.05, 0.00],
    )

    cbar.set_label(
        "Δ Macro-F1 vs Proposed",
        fontsize=9.5,
        # fontweight="bold",
    )

    cbar.ax.tick_params(
        labelsize=9.5,
        width=1.0,
        length=3.5,
    )

    cbar.outline.set_linewidth(1.0)

    # -------------------------
    # 标题与坐标轴标题：保留
    # -------------------------
    # ax.set_title(
    #     "Fig. 5b | Task-wise loss in Macro-F1 after framework-level ablation",
    #     fontsize=13.0,
    #     fontweight="bold",
    #     pad=14,
    # )

    ax.set_xlabel(
        "Tasks",
        fontsize=11,
        fontweight="bold",
        labelpad=6,
    )

    ax.set_ylabel(
        "Ablated component",
        fontsize=11,
        fontweight="bold",
        labelpad=4,
    )

    # -------------------------
    # 去掉外框
    # -------------------------
    for spine in ax.spines.values():
        spine.set_visible(False)

    plt.subplots_adjust(
        left=0.25,
        right=0.90,
        top=0.84,
        bottom=0.23,
    )

    return fig


# ============================================================
# 7. 主程序
# ============================================================

def main():
    df = load_fig5b_data(EXCEL_PATH, SHEET_NAME)
    value_mat, sd_mat = build_matrix(df)

    print("\n[Fig5b matrix | Δ Macro-F1]")
    print(value_mat)

    fig = plot_heatmap(value_mat, sd_mat)

    out_png = OUTPUT_DIR / f"{OUTPUT_BASENAME}.png"
    out_pdf = OUTPUT_DIR / f"{OUTPUT_BASENAME}.pdf"
    out_svg = OUTPUT_DIR / f"{OUTPUT_BASENAME}.svg"

    fig.savefig(out_png, dpi=DPI, bbox_inches="tight")
    fig.savefig(out_pdf, bbox_inches="tight")
    fig.savefig(out_svg, bbox_inches="tight")
    plt.close(fig)

    print("\n[完成] Fig5b heatmap 已保存：")
    print(f"  - {out_png}")
    print(f"  - {out_pdf}")
    print(f"  - {out_svg}")


if __name__ == "__main__":
    main()
