# -*- coding: utf-8 -*-
"""
Plot Fig. 5c | AUPRC of binary structured CPET interpretation tasks under framework-level ablations.

Input:
    Excel generated by result5_framework_ablation_summary_v4.py
    Sheet: Fig5c_auprc_t3_t5

Output:
    Fig5c_auprc_t3_t5.png
    Fig5c_auprc_t3_t5.pdf
    Fig5c_auprc_t3_t5.svg

Figure design:
    - Three panels:
        c(i)   t3 AUPRC
        c(ii)  t4 AUPRC
        c(iii) t5 AUPRC
    - Bars: Proposed + framework-level ablations
    - Dashed horizontal line: random baseline AUPRC = positive prevalence
"""

from pathlib import Path
import re

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# 1. 路径配置：主要修改这里
# ============================================================

EXCEL_PATH = Path(
    r"xx_path"
)

SHEET_NAME = "Fig5c_auprc_t3_t5"

OUTPUT_DIR = EXCEL_PATH.parent
OUTPUT_BASENAME = "Fig5c_auprc_t3_t5"


# ============================================================
# 2. 任务与随机基线
# ============================================================

TASK_ORDER = ["t3", "t4", "t5"]

TASK_DISPLAY_NAME = {
    "t3": "t3\nExercise ECG\nresponse",
    "t4": "t4\nbreathing\nreserve",
    "t5": "t5\nHeart-rate\nreserve",
}

PANEL_TITLE = {
    "t3": "t3: Exercise ECG response",
    "t4": "t4: Breathing reserve",
    "t5": "t5: Heart-rate reserve",
}
# 随机基线 AUPRC = positive prevalence = minority samples / N
RANDOM_BASELINE_AUPRC = {
    "t3": 0.0881,  # 20 / 227
    "t4": 0.3172,  # 72 / 227
    "t5": 0.2026,  # 46 / 227
}


# ============================================================
# 3. 模型显示顺序与颜色
# ============================================================

MODEL_ORDER = [
    "Proposed",
    "w/o T6-Ctx",
    "w/o αβ-Routing",
    "w/o β-Experts",
    "w/o 9P-Prior",
]

# 蓝灰色系：包含用户指定色块及相近色
MODEL_COLOR_MAP = {
    "Proposed": "#2C7FB8",       # 深蓝
    "w/o T6-Ctx": "#7FA6C7",      # 浅蓝
    "w/o αβ-Routing": "#B8B8B8",   # 中灰
    "w/o β-Experts": "#A6BDDB",    # 蓝灰
    "w/o 9P-Prior": "#D0D0D0", # 浅灰
}

EXPERIMENT_TO_DISPLAY = {
    "Full": "Proposed",
    "E1": "w/o T6-Ctx",
    "E2": "w/o αβ-Routing",
    "E3": "w/o β-Experts",
    "E4": "w/o 9P-Prior",
    "S6": "w/o 9P-Prior",
}

MODEL_TICK_LABEL = {
    "Proposed": "Proposed",
    "w/o T6-Ctx": "w/o\nT6-Ctx",
    "w/o αβ-Routing": "w/o\nαβ-Routing",
    "w/o β-Experts": "w/o\nβ-Experts",
    "w/o 9P-Prior": "w/o\n9P-Prior",
}

# ============================================================
# 4. 绘图参数
# ============================================================

plt.rcParams["font.family"] = "Arial"
plt.rcParams["font.size"] = 9
plt.rcParams["axes.linewidth"] = 0.8
plt.rcParams["pdf.fonttype"] = 42
plt.rcParams["ps.fonttype"] = 42

FIGSIZE = (8.0, 4.1)
DPI = 600

BAR_WIDTH = 0.68
ERRORBAR_CAPSIZE = 3


# ============================================================
# 5. 工具函数
# ============================================================

def normalize_text(x):
    if pd.isna(x):
        return ""
    return str(x).strip()


def parse_numeric(x):
    """
    支持：
    - float/int
    - '0.1234'
    - '0.1234 ± 0.0123'
    """
    if pd.isna(x):
        return np.nan

    if isinstance(x, (int, float, np.number)):
        return float(x)

    s = str(x).strip().replace("−", "-")
    if not s:
        return np.nan

    m = re.search(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", s)
    if not m:
        return np.nan

    return float(m.group(0))


def find_col(df, candidates, required=True):
    lower_map = {str(c).strip().lower(): c for c in df.columns}

    for cand in candidates:
        key = str(cand).strip().lower()
        if key in lower_map:
            return lower_map[key]

    norm_candidates = [
        re.sub(r"\s+", "", str(c).lower().replace("–", "-").replace("—", "-"))
        for c in candidates
    ]

    for col in df.columns:
        norm_col = re.sub(r"\s+", "", str(col).lower().replace("–", "-").replace("—", "-"))
        if norm_col in norm_candidates:
            return col

    if required:
        raise ValueError(f"找不到列：{candidates}\n当前列：{list(df.columns)}")

    return None


def infer_display_name(experiment, model_variant):
    experiment = normalize_text(experiment)
    model_variant = normalize_text(model_variant)

    if experiment in EXPERIMENT_TO_DISPLAY:
        return EXPERIMENT_TO_DISPLAY[experiment]

    lower = model_variant.lower()

    if "proposed" in lower:
        return "Proposed"
    if "t6" in lower and "context" in lower:
        return "No T6-ctx"
    if "dual" in lower or "single-alpha" in lower or "single alpha" in lower:
        return "Single-Alpha"
    if "beta" in lower:
        return "Shared-Beta"
    if "prior" in lower or "nine-panel" in lower:
        return "No Prior-chain"

    return model_variant


def load_fig5c_data(excel_path, sheet_name):
    df = pd.read_excel(excel_path, sheet_name=sheet_name)

    task_col = find_col(df, ["Task", "task"], required=True)
    exp_col = find_col(df, ["Experiment"], required=False)
    variant_col = find_col(df, ["Model variant", "model_variant"], required=False)

    auprc_mean_col = find_col(df, [
        "AUPRC mean",
        "auprc mean",
        "AUPRC",
        "auprc",
    ], required=True)

    auprc_sd_col = find_col(df, [
        "AUPRC SD",
        "auprc SD",
        "AUPRC sd",
        "auprc sd",
    ], required=False)

    rows = []
    for _, row in df.iterrows():
        task = normalize_text(row[task_col])
        if task not in TASK_ORDER:
            continue

        exp = normalize_text(row[exp_col]) if exp_col else ""
        variant = normalize_text(row[variant_col]) if variant_col else ""

        display = infer_display_name(exp, variant)
        if display not in MODEL_ORDER:
            continue

        rows.append({
            "Task": task,
            "Experiment": exp,
            "Model variant": variant,
            "Display name": display,
            "AUPRC mean": parse_numeric(row[auprc_mean_col]),
            "AUPRC SD": parse_numeric(row[auprc_sd_col]) if auprc_sd_col else np.nan,
        })

    out = pd.DataFrame(rows)

    if out.empty:
        raise ValueError(
            "Fig5c 数据为空。请检查 Fig5c_auprc_t3_t5 sheet 是否包含 "
            "Task / Experiment / Model variant / AUPRC mean 等列。"
        )

    out["Task"] = pd.Categorical(out["Task"], categories=TASK_ORDER, ordered=True)
    out["Display name"] = pd.Categorical(out["Display name"], categories=MODEL_ORDER, ordered=True)

    # 避免 E4/S6 命名混用导致重复：同一 task × display 只保留第一条
    out = (
        out.sort_values(["Task", "Display name"])
        .drop_duplicates(subset=["Task", "Display name"], keep="first")
        .reset_index(drop=True)
    )

    return out


def get_panel_ylim(task, vals, baseline):
    vals = [v for v in vals if pd.notna(v)]
    vals.append(baseline)

    # t4 / t5 固定显示到 1.0，补出 1.0 的刻度与网格线
    if task in ["t4", "t5"]:
        return 0, 1.0

    # t3 单独自适应
    vmax = max(vals) if vals else baseline
    top = max(0.25, vmax * 1.22 + 0.02)
    top = min(top, 1.0)

    return 0, top


# ============================================================
# 6. 绘图函数
# ============================================================

def draw_task_panel(ax, df_task, task,panel_idx=0):
    baseline = RANDOM_BASELINE_AUPRC[task]

    # 保证完整模型顺序
    df_task = (
        df_task.set_index("Display name")
        .reindex(MODEL_ORDER)
        .reset_index()
        .rename(columns={"index": "Display name"})
    )

    x = np.arange(len(MODEL_ORDER))
    means = df_task["AUPRC mean"].to_numpy(dtype=float)
    sds = df_task["AUPRC SD"].to_numpy(dtype=float)

    colors = [MODEL_COLOR_MAP[m] for m in MODEL_ORDER]

    bars = ax.bar(
        x,
        means,
        width=BAR_WIDTH,
        color=colors,
        edgecolor="black",
        linewidth=0.6,
        zorder=2,
    )

    # 误差线
    for i, (mean, sd) in enumerate(zip(means, sds)):
        if pd.notna(mean) and pd.notna(sd):
            ax.errorbar(
                i,
                mean,
                yerr=sd,
                fmt="none",
                ecolor="black",
                elinewidth=0.9,
                capsize=ERRORBAR_CAPSIZE,
                capthick=0.9,
                zorder=3,
            )

    # 随机基线
    ax.axhline(
        baseline,
        color="#555555",
        linestyle="--",
        linewidth=1.0,
        alpha=0.9,
        zorder=1,
    )

    baseline_text_y_offset = 0.008
    if panel_idx == 0:
        baseline_text_y_offset = 0.03
    if panel_idx==1:
        baseline_text_y_offset = 0.1
    if panel_idx==2:
        baseline_text_y_offset = 0.1
    
    ax.text(
        len(MODEL_ORDER) - 0.5,
        baseline - baseline_text_y_offset,
        f"Random baseline = {baseline:.4f}",
        ha="right",
        va="bottom",
        fontsize=7.5,
        color="#444444",
    )

    # 数值标注
    for i, mean in enumerate(means):
        if pd.notna(mean):
            ax.text(
                i-0.02,
                mean + 0.025,
                f"{mean:.3f}",
                ha="center",
                va="bottom",
                fontsize=7.5,
                rotation=0,
            )

    ax.set_title(PANEL_TITLE[task], fontsize=10, fontweight="bold", pad=8)
    ax.set_xticks(x)
    ax.set_xticklabels([MODEL_TICK_LABEL[m] for m in MODEL_ORDER], rotation=25, ha="right", fontsize=8)
    ax.tick_params(
        axis="x",
        bottom=True,
        top=False,
        labelbottom=True,
        width=1.0,
        length=3.5,
        pad=0,
    )

    ymin, ymax = get_panel_ylim(task, means.tolist(), baseline)
    ax.set_ylim(ymin, ymax)

    ax.grid(axis="y", linestyle="--", linewidth=0.5, alpha=0.35)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    ax.set_ylabel("AUPRC" if task == "t3" else "", fontsize=10,fontweight="bold")


def plot_fig5c(df):
    fig, axes = plt.subplots(
        1,
        3,
        figsize=FIGSIZE,
        sharey=False,
        constrained_layout=False,
    )

    for i, (ax, task) in enumerate(zip(axes, TASK_ORDER)):
        df_task = df[df["Task"].astype(str) == task].copy()
        draw_task_panel(ax, df_task, task,panel_idx=i)

    # fig.suptitle(
    #     "Fig. 5c | AUPRC of binary CPET interpretation tasks after framework-level ablation",
    #     fontsize=11,
    #     fontweight="bold",
    #     y=0.98,
    # )
    fig.supxlabel(
        "Ablated component",
        fontsize=10,
        fontweight="bold",
        y=0.09,
    )

    #plt.subplots_adjust(left=0.08, right=0.99, top=0.80, bottom=0.28, wspace=0.28)
    plt.subplots_adjust(
        left=0.075,
        right=0.99,
        top=0.86,
        bottom=0.24,
        wspace=0.30,
    )

    return fig


# ============================================================
# 7. 主函数
# ============================================================

def main():
    df = load_fig5c_data(EXCEL_PATH, SHEET_NAME)
    fig = plot_fig5c(df)

    out_png = OUTPUT_DIR / f"{OUTPUT_BASENAME}.png"
    out_pdf = OUTPUT_DIR / f"{OUTPUT_BASENAME}.pdf"
    out_svg = OUTPUT_DIR / f"{OUTPUT_BASENAME}.svg"

    fig.savefig(out_png, dpi=DPI, bbox_inches="tight")
    fig.savefig(out_pdf, bbox_inches="tight")
    fig.savefig(out_svg, bbox_inches="tight")
    plt.close(fig)

    print("[完成] Fig5c AUPRC 图已保存：")
    print(f"  - {out_png}")
    print(f"  - {out_pdf}")
    print(f"  - {out_svg}")


if __name__ == "__main__":
    main()
