# -*- coding: utf-8 -*-
"""
Plot Fig. 5a | Overall performance loss of framework-level ablations.

Input:
    Result5 summary Excel generated by result5_framework_ablation_summary_v4.py
    Sheet: Fig5a_overall_loss

Output:
    Fig5a_overall_loss.png
    Fig5a_overall_loss.pdf
    Fig5a_overall_loss.svg

Figure design:
    - Two horizontal lollipop panels:
        i)  Δ t1–t5 mean Macro-F1
        ii) Δ t1–t5 mean Accuracy
    - Δ = ablation variant − Proposed framework
    - x = 0 indicates the full proposed framework reference.
"""

from pathlib import Path
import re

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# 1. 路径配置：主要修改这里
# ============================================================

EXCEL_PATH = Path(
    r"xx_path"
)

SHEET_NAME = "Fig5a_overall_loss"

OUTPUT_DIR = EXCEL_PATH.parent
OUTPUT_BASENAME = "Fig5a_overall_loss"


# ============================================================
# 2. 颜色配置：参考 Fig2 配色
# ============================================================

ABLATION_COLOR_MAP = {
    "Proposed": "#D62728",          # 红色
    "w/o T6-Ctx": "#8C564B",       # 棕色
    "w/o αβ-Routing": "#FF7F0E",   # 橙色
    "w/o β-Experts": "#9467BD",    # 紫色
    "w/o 9P-Prior": "#2CA02C",     # 绿色
}

# 展示顺序
DISPLAY_ORDER = [
    "w/o 9P-Prior",
    "w/o β-Experts",
    "w/o αβ-Routing",
    "w/o T6-Ctx",
]

# 实验编号到显示名称
EXPERIMENT_TO_DISPLAY = {
    "E1": "w/o T6-Ctx",
    "E2": "w/o αβ-Routing",
    "E3": "w/o β-Experts",
    "E4": "w/o 9P-Prior",
    "Full": "Proposed",
}


# ============================================================
# 3. 绘图参数
# ============================================================

# ============================================================
# 3. 绘图参数：统一 Fig2C 风格
# ============================================================

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "DejaVu Serif"],
    "font.size": 10.5,
    "axes.titlesize": 11.5,
    "axes.labelsize": 11,
    "xtick.labelsize": 9.5,
    "ytick.labelsize": 9.5,
    "legend.fontsize": 9.5,
    "axes.linewidth": 1.0,
    "xtick.major.width": 1.0,
    "ytick.major.width": 1.0,
    "xtick.major.size": 3.5,
    "ytick.major.size": 3.5,
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
    "svg.fonttype": "none",
})

FIGSIZE = (6.6, 3.2)
POINT_SIZE = 58
LINE_WIDTH = 2.2
ERRORBAR_CAPSIZE = 3
DPI = 600


# ============================================================
# 4. 工具函数
# ============================================================

def normalize_text(x):
    if pd.isna(x):
        return ""
    return str(x).strip()


def parse_numeric(x):
    """
    支持：
    - float/int
    - '0.1234'
    - '-0.1234'
    - '0.1234 ± 0.0123'
    """
    if pd.isna(x):
        return np.nan
    if isinstance(x, (int, float, np.number)):
        return float(x)

    s = str(x).strip()
    if not s:
        return np.nan

    # 如果是 mean ± SD，只取 mean
    s = s.replace("−", "-")
    m = re.search(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", s)
    if not m:
        return np.nan
    return float(m.group(0))

def format_ablation_ylabel(name):
    """
    将 y 轴标签中的 w/o 单独放在第一行。
    例如：
    w/o 9P-Prior -> w/o\n9P-Prior
    """
    name = str(name)
    if name.startswith("w/o "):
        return name.replace("w/o ", "w/o\n", 1)
    return name

def find_col(df, candidates, required=True):
    """
    在 df 中按候选名寻找列。
    兼容空格、大小写和部分不同写法。
    """
    col_map = {str(c).strip().lower(): c for c in df.columns}

    for cand in candidates:
        key = str(cand).strip().lower()
        if key in col_map:
            return col_map[key]

    # 模糊匹配
    norm_candidates = [
        re.sub(r"\s+", "", str(c).strip().lower().replace("–", "-").replace("—", "-"))
        for c in candidates
    ]
    for col in df.columns:
        norm_col = re.sub(r"\s+", "", str(col).strip().lower().replace("–", "-").replace("—", "-"))
        if norm_col in norm_candidates:
            return col

    if required:
        raise ValueError(f"找不到所需列。候选列名：{candidates}\n当前列：{list(df.columns)}")
    return None


def infer_display_name(row):
    exp = normalize_text(row.get("Experiment", ""))
    variant = normalize_text(row.get("Model variant", ""))

    if exp in EXPERIMENT_TO_DISPLAY:
        return EXPERIMENT_TO_DISPLAY[exp]

    lower = variant.lower()
    if "t6" in lower and "context" in lower:
        return "No T6-ctx"
    if "dual" in lower or "single-alpha" in lower or "single alpha" in lower:
        return "Single-Alpha"
    if "beta" in lower and ("expert" in lower or "shared" in lower):
        return "Shared-Beta"
    if "prior" in lower or "nine-panel" in lower:
        return "No Prior-chain"
    if "proposed" in lower:
        return "Proposed"

    return variant


def load_fig5a_data(excel_path, sheet_name):
    """
    读取 Fig5a_overall_loss。

    兼容两种结构：
    1. 宽表：
       Model variant | Experiment |
       Δ t1–t5 mean Macro-F1 mean | Δ t1–t5 mean Macro-F1 SD |
       Δ t1–t5 mean Accuracy mean | Δ t1–t5 mean Accuracy SD

    2. 较简表：
       Model variant | Experiment | Δ mean Macro-F1 | Δ mean Accuracy
       此时 SD 会为空。
    """
    df = pd.read_excel(excel_path, sheet_name=sheet_name)

    # 去掉 Proposed / Full 参考行，只画消融变体
    df["Display name"] = df.apply(infer_display_name, axis=1)
    df = df[df["Display name"] != "Proposed"].copy()

    # 列名兼容
    macro_mean_col = find_col(df, [
        "Δ t1–t5 mean Macro-F1 mean",
        "Delta t1–t5 mean Macro-F1 mean",
        "Δ mean Macro-F1 mean",
        "Delta mean Macro-F1 mean",
        "Δ mean Macro-F1",
        "Delta mean Macro-F1",
    ], required=False)

    macro_sd_col = find_col(df, [
        "Δ t1–t5 mean Macro-F1 SD",
        "Delta t1–t5 mean Macro-F1 SD",
        "Δ mean Macro-F1 SD",
        "Delta mean Macro-F1 SD",
    ], required=False)

    acc_mean_col = find_col(df, [
        "Δ t1–t5 mean Accuracy mean",
        "Delta t1–t5 mean Accuracy mean",
        "Δ mean Accuracy mean",
        "Delta mean Accuracy mean",
        "Δ mean Accuracy",
        "Delta mean Accuracy",
    ], required=False)

    acc_sd_col = find_col(df, [
        "Δ t1–t5 mean Accuracy SD",
        "Delta t1–t5 mean Accuracy SD",
        "Δ mean Accuracy SD",
        "Delta mean Accuracy SD",
    ], required=False)

    if macro_mean_col is None or acc_mean_col is None:
        raise ValueError(
            "无法识别 Fig5a 所需的 Δ Macro-F1 / Δ Accuracy 列。\n"
            f"当前列名：{list(df.columns)}"
        )

    rows = []
    for _, row in df.iterrows():
        display = row["Display name"]
        rows.append({
            "Display name": display,
            "Experiment": normalize_text(row.get("Experiment", "")),
            "Model variant": normalize_text(row.get("Model variant", "")),
            "Delta Macro-F1 mean": parse_numeric(row[macro_mean_col]),
            "Delta Macro-F1 SD": parse_numeric(row[macro_sd_col]) if macro_sd_col else np.nan,
            "Delta Accuracy mean": parse_numeric(row[acc_mean_col]),
            "Delta Accuracy SD": parse_numeric(row[acc_sd_col]) if acc_sd_col else np.nan,
        })

    out = pd.DataFrame(rows)

    # 按 DISPLAY_ORDER 排序
    order_map = {name: i for i, name in enumerate(DISPLAY_ORDER)}
    out["order"] = out["Display name"].map(order_map)
    out = out[out["Display name"].isin(DISPLAY_ORDER)].sort_values("order").reset_index(drop=True)
    out = out.drop(columns=["order"])

    if out.empty:
        raise ValueError("读取后没有找到需要绘制的消融实验。请检查 Experiment / Model variant 命名。")

    return out


def nice_xlim(values, sds=None):
    vals = [v for v in values if pd.notna(v)]
    if sds is not None:
        for v, sd in zip(values, sds):
            if pd.notna(v) and pd.notna(sd):
                vals.append(v - sd)
                vals.append(v + sd)

    if not vals:
        return (-0.1, 0.02)

    vmin = min(vals)
    vmax = max(vals)

    # Δ 通常为负，右侧留出一点空间给 0 参考线
    right = max(0.015, vmax + 0.01)
    left = min(vmin - 0.02, -0.02)

    # 防止过窄
    if right - left < 0.06:
        mid = (right + left) / 2
        left = mid - 0.04
        right = mid + 0.04

    return left, right


def draw_lollipop_panel(ax, df, mean_col, sd_col, title, xlabel):
    y = np.arange(len(df))

    values = df[mean_col].to_numpy(dtype=float)
    sds = df[sd_col].to_numpy(dtype=float) if sd_col in df.columns else np.full_like(values, np.nan)

    for i, row in df.iterrows():
        name = row["Display name"]
        value = row[mean_col]
        sd = row[sd_col] if sd_col in row else np.nan
        color = ABLATION_COLOR_MAP.get(name, "#666666")

        # reference line from 0 to delta
        ax.hlines(
            y=i,
            xmin=0,
            xmax=value,
            color=color,
            linewidth=LINE_WIDTH,
            alpha=0.95,
        )

        # point + errorbar
        if pd.notna(sd):
            ax.errorbar(
                value,
                i,
                xerr=sd,
                fmt="o",
                markersize=6,
                color=color,
                ecolor=color,
                elinewidth=1.2,
                capsize=ERRORBAR_CAPSIZE,
                markeredgecolor="black",
                markeredgewidth=0.5,
                zorder=3,
            )
        else:
            ax.scatter(
                value,
                i,
                s=POINT_SIZE,
                color=color,
                edgecolor="black",
                linewidth=0.5,
                zorder=3,
            )

        # value label
        if pd.notna(value):
            ax.text(
                value - 0.004 if value < 0 else value + 0.004,
                i + 0.18,
                f"{value:.4f}",
                ha="right" if value < 0 else "left",
                va="center",
                fontsize=8.5,
                color="black",
            )

    ax.axvline(0, color="black", linewidth=0.9, linestyle="--", alpha=0.75)
    ax.set_yticks(y)
    ax.set_yticklabels(
        [format_ablation_ylabel(x) for x in df["Display name"].tolist()],
        linespacing=1.05,
    )


    # ax.set_title(title, fontsize=11.5, fontweight="bold", pad=15)
    ax.set_xlabel(xlabel, fontsize=11, fontweight="bold")

    left, right = nice_xlim(values, sds)
    ax.set_xlim(left, right)

    ax.grid(axis="x", linestyle="--", linewidth=0.5, alpha=0.35)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


# ============================================================
# 5. 主函数
# ============================================================

def main():
    df = load_fig5a_data(EXCEL_PATH, SHEET_NAME)

    fig, axes = plt.subplots(
        1,
        2,
        figsize=FIGSIZE,
        sharey=True,
        constrained_layout=False,
    )

    draw_lollipop_panel(
        axes[0],
        df,
        mean_col="Delta Macro-F1 mean",
        sd_col="Delta Macro-F1 SD",
        title="Δ mean Macro-F1",
        xlabel="Δ Macro-F1 vs Proposed",
    )

    draw_lollipop_panel(
        axes[1],
        df,
        mean_col="Delta Accuracy mean",
        sd_col="Delta Accuracy SD",
        title="Δ mean Accuracy",
        xlabel="Δ Accuracy vs Proposed",
    )

    # 第二个 panel 不重复 y 轴标签
    axes[1].tick_params(
        axis="y",
        which="major",
        left=True,
        labelleft=False,
        length=3.5,
        width=1.0,
        direction="out",
        labelsize=9.5,
    )

    axes[0].set_ylabel(
        "Ablated component",
        fontsize=11,
        fontweight="bold",
        labelpad=4,
    )

    # fig.suptitle(
    #     "Fig. 5a | Overall performance loss after framework-level ablation",
    #     fontsize=13.5,
    #     fontweight="bold",
    #     y=0.98,
    # )

    plt.subplots_adjust(left=0.22, right=0.98, top=0.82, bottom=0.20, wspace=0.1)

    out_png = OUTPUT_DIR / f"{OUTPUT_BASENAME}.png"
    out_pdf = OUTPUT_DIR / f"{OUTPUT_BASENAME}.pdf"
    out_svg = OUTPUT_DIR / f"{OUTPUT_BASENAME}.svg"

    fig.savefig(out_png, dpi=DPI, bbox_inches="tight")
    fig.savefig(out_pdf, bbox_inches="tight")
    fig.savefig(out_svg, bbox_inches="tight")
    plt.close(fig)

    print("[完成] Fig5a 已保存：")
    print(f"  - {out_png}")
    print(f"  - {out_pdf}")
    print(f"  - {out_svg}")


if __name__ == "__main__":
    main()
