# -*- coding: utf-8 -*-
"""
Plot Result 1.7 subgroup main figure: task-wise robustness across age, sex,
and disease-mechanism subgroups.

Input
-----
An Excel file generated by `build_subgroup_task_profile_tables.py`, containing
sheet `Fig_subgroup_task_profile_data` with columns such as:
    panel, panel_order, metric, metric_panel_order, subgroup_label,
    subgroup_order, task, task_order, mean, sd, errorbar_in_main,
    is_reference, line_color, line_style, marker,
    recommended_ymin, recommended_ymax

Final figure layout
-------------------
Figure X | Task-wise robustness across age, sex, and disease-mechanism subgroups.
- 3 columns: Age, Sex, T6 disease mechanism
- 2 rows: Accuracy, Macro-F1
- x-axis: t1, t2, t3, t4, t5, Mean
- subgroup lines: age/sex/t6 groups
- full overall holdout cohort: black dashed reference line in each panel
- error bars: only shown for the final Mean across t1-t5 point by default

Usage
-----
python plot_subgroup_task_profile_main.py \
  --input "xx_path" \
  --out_dir "xx_path"

Outputs
-------
- Fig_subgroup_task_profile_main.png
- Fig_subgroup_task_profile_main.pdf
- Fig_subgroup_task_profile_main.svg
- Fig_subgroup_task_profile_main.tiff
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


# =============================================================================
# 0. User configuration
# =============================================================================

DEFAULT_INPUT = Path(
    r"xx_path"
)
DEFAULT_SHEET = "Fig_subgroup_task_profile_data"
DEFAULT_OUT_DIR = Path(
    r"xx_path"
)
DEFAULT_PREFIX = "Fig_subgroup_task_profile_main"

# Final task order used in the main figure.
TASK_ORDER = ["t1", "t2", "t3", "t4", "t5", "Mean across t1–t5"]
TASK_SHORT_LABEL = {
    "t1": "t1",
    "t2": "t2",
    "t3": "t3",
    "t4": "t4",
    "t5": "t5",
    "Mean across t1–t5": "Mean",
    "Mean across t1-t5": "Mean",
}

# Panel and metric orders.
PANEL_ORDER = ["Age", "Sex", "T6 disease mechanism"]
PANEL_TITLE = {
    "Age": "Age subgroup",
    "Sex": "Sex subgroup",
    "T6 disease mechanism": "Disease-mechanism subgroup",
}
PANEL_LETTER = {
    "Age": "a",
    "Sex": "b",
    "T6 disease mechanism": "c",
}
METRIC_ORDER = ["Accuracy", "Macro-F1"]

# Y-axis limits; rows share the same limits across three columns.
DEFAULT_YLIM = {
    "Accuracy": (0.68, 1.01),
    "Macro-F1": (0.45, 1.01),
}

# Fallback line styles if the input sheet does not provide style columns.
FALLBACK_COLORS = {
    # Age
    "Age <30": "#A6C8E8",
    "Age 30-39": "#BBD3E9",
    "Age 40-49": "#6FA8DC",
    "Age 50-59": "#2F75B5",
    "Age 60-69": "#1F4E79",
    "Age ≥70": "#1F4E79",
    # Sex
    "Female": "#9B59B6",
    "Male": "#2CA6A4",
    # T6
    "CMP": "#2C7FB8",
    "HTx": "#70AD47",
    "IHD": "#F4B183",
    "PVD": "#C55A9E",
}
FALLBACK_PANEL_GROUP_ORDER = {
    "Age": [ "Age <30", "Age 30-39", "Age 40-49", "Age 50-59", "Age 60-69", "Age ≥70"],
    "Sex": ["Female", "Male"],
    "T6 disease mechanism": ["CMP", "HTx", "IHD", "PVD"],
}


# =============================================================================
# 1. Data utilities
# =============================================================================

def parse_bool(value) -> bool:
    """Robust boolean parser for values imported from Excel."""
    if isinstance(value, bool):
        return value
    if pd.isna(value):
        return False
    s = str(value).strip().lower()
    return s in {"true", "1", "yes", "y", "t"}


def normalize_task_name(task: str) -> str:
    """Normalize possible hyphen variants in the mean label."""
    s = str(task).strip()
    if s in {"Mean", "mean", "Mean across t1-t5", "Mean across t1–t5"}:
        return "Mean across t1–t5"
    return s


def ensure_required_columns(df: pd.DataFrame) -> None:
    required = ["panel", "metric", "subgroup_label", "task", "mean"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(
            "Input sheet is missing required columns: " + ", ".join(missing)
        )


def load_profile_data(xlsx_path: Path, sheet_name: str) -> pd.DataFrame:
    if not xlsx_path.exists():
        raise FileNotFoundError(f"Input Excel not found: {xlsx_path}")

    df = pd.read_excel(xlsx_path, sheet_name=sheet_name)
    ensure_required_columns(df)

    df = df.copy()
    df["task"] = df["task"].apply(normalize_task_name)
    df["mean"] = pd.to_numeric(df["mean"], errors="coerce")
    if "sd" in df.columns:
        df["sd"] = pd.to_numeric(df["sd"], errors="coerce")
    else:
        df["sd"] = np.nan

    if "task_order" not in df.columns:
        order_map = {t: i + 1 for i, t in enumerate(TASK_ORDER)}
        df["task_order"] = df["task"].map(order_map)
    if "subgroup_order" not in df.columns:
        df["subgroup_order"] = np.nan
    if "metric_panel_order" not in df.columns:
        df["metric_panel_order"] = df["metric"].map({"Accuracy": 1, "Macro-F1": 2})
    if "panel_order" not in df.columns:
        df["panel_order"] = df["panel"].map({p: i + 1 for i, p in enumerate(PANEL_ORDER)})
    if "is_reference" not in df.columns:
        df["is_reference"] = df["subgroup_label"].astype(str).str.contains("Full", case=False, na=False)
    if "errorbar_in_main" not in df.columns:
        df["errorbar_in_main"] = df["task"].eq("Mean across t1–t5")
    if "line_color" not in df.columns:
        df["line_color"] = df["subgroup_label"].map(FALLBACK_COLORS).fillna("#666666")
    if "line_style" not in df.columns:
        df["line_style"] = np.where(df["is_reference"].apply(parse_bool), "--", "-")
    if "marker" not in df.columns:
        df["marker"] = "o"

    # Keep only final main figure metrics and task order.
    df = df[df["metric"].isin(METRIC_ORDER)]
    df = df[df["task"].isin(TASK_ORDER)]

    return df


def ordered_groups(panel_df: pd.DataFrame, panel_name: str) -> List[str]:
    """Return subgroup labels ordered by subgroup_order, with fallback order."""
    tmp = (
        panel_df[["subgroup_label", "subgroup_order"]]
        .drop_duplicates()
        .copy()
    )
    tmp["subgroup_order"] = pd.to_numeric(tmp["subgroup_order"], errors="coerce")

    if tmp["subgroup_order"].notna().any():
        tmp = tmp.sort_values(["subgroup_order", "subgroup_label"])
        labels = tmp["subgroup_label"].astype(str).tolist()
    else:
        present = set(tmp["subgroup_label"].astype(str))
        fallback = [g for g in FALLBACK_PANEL_GROUP_ORDER.get(panel_name, []) if g in present]
        rest = sorted(list(present - set(fallback)))
        labels = fallback + rest

    # Ensure Full cohort appears first if available.
    full_like = [g for g in labels if str(g).lower() == "full cohort"]
    if full_like:
        labels = full_like + [g for g in labels if g not in full_like]
    return labels


def get_style(group_df: pd.DataFrame, group_label: str) -> Tuple[str, str, str, bool]:
    """Read color/style/marker/reference flag from group rows."""
    row = group_df.iloc[0]
    color = row.get("line_color", FALLBACK_COLORS.get(group_label, "#666666"))
    if pd.isna(color) or str(color).strip() == "":
        color = FALLBACK_COLORS.get(group_label, "#666666")

    is_ref = parse_bool(row.get("is_reference", group_label == "Full cohort"))
    line_style = row.get("line_style", "--" if is_ref else "-")
    if pd.isna(line_style) or str(line_style).strip() == "":
        line_style = "--" if is_ref else "-"

    marker = row.get("marker", "o")
    if pd.isna(marker) or str(marker).strip() == "":
        marker = "o"

    return str(color), str(line_style), str(marker), is_ref


def values_for_group(group_df: pd.DataFrame) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return x, y, sd arrays in final task order."""
    task_to_x = {t: i for i, t in enumerate(TASK_ORDER)}
    xs, ys, yerrs = [], [], []
    for task in TASK_ORDER:
        sub = group_df[group_df["task"] == task]
        if sub.empty:
            xs.append(task_to_x[task])
            ys.append(np.nan)
            yerrs.append(np.nan)
            continue
        row = sub.iloc[0]
        xs.append(task_to_x[task])
        ys.append(float(row["mean"]) if pd.notna(row["mean"]) else np.nan)
        yerrs.append(float(row["sd"]) if pd.notna(row.get("sd", np.nan)) else np.nan)
    return np.asarray(xs), np.asarray(ys), np.asarray(yerrs)


# =============================================================================
# 2. Plot utilities
# =============================================================================

def configure_matplotlib(font_family: str = "Arial") -> None:
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": [font_family, "DejaVu Sans", "Liberation Sans"],
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "axes.linewidth": 1.0,
        "axes.labelsize": 10.5,
        "axes.titlesize": 12,
        "xtick.labelsize": 9.5,
        "ytick.labelsize": 9.5,
        "legend.fontsize": 8.8,
        "figure.dpi": 120,
        "savefig.dpi": 600,
    })


def prettify_axis(ax: plt.Axes, metric: str, show_xlabel: bool = True) -> None:
    x_positions = np.arange(len(TASK_ORDER))
    ax.set_xticks(x_positions)
    ax.set_xticklabels([TASK_SHORT_LABEL.get(t, t) for t in TASK_ORDER])
    ax.set_xlim(-0.35, len(TASK_ORDER) - 0.65)
    ax.axvline(4.5, color="#D0D0D0", linestyle="--", linewidth=0.9, zorder=0)

    # Row-wise y-axis limits.
    ymin, ymax = DEFAULT_YLIM.get(metric, (0.0, 1.0))
    ax.set_ylim(ymin, ymax)

    ax.set_ylabel(metric, fontweight="bold")
    if show_xlabel:
        ax.set_xlabel("Task", fontweight="bold")
    else:
        ax.set_xlabel("")

    ax.grid(axis="y", color="#EAEAEA", linewidth=0.8)
    ax.grid(axis="x", visible=False)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


    ax.tick_params(axis="both", direction="out", length=3.5, width=0.9)

    # 强制所有子图都显示 x 轴刻度标签，包括上排 Accuracy 子图
    ax.tick_params(
        axis="x",
        labelsize=11.5,
        labelbottom=True,
        bottom=True,
    )

    # 强制所有子图都显示 y 轴刻度标签，包括 b/c 两列
    ax.tick_params(
        axis="y",
        labelsize=11.5,
        labelleft=True,
        left=True,
    )


def make_panel_legend(ax: plt.Axes, handles: List[Line2D], ncol: int) -> None:
    ax.legend(
        handles=handles,
        loc="center",
        bbox_to_anchor=(0.5, 0.93),
        frameon=False,
        ncol=ncol,
        fontsize=10,
        handlelength=2.2,
        columnspacing=1.0,
        borderaxespad=0.0,
    )


def plot_single_axis(
    ax: plt.Axes,
    df: pd.DataFrame,
    panel_name: str,
    metric: str,
    show_errorbar: bool = True,
    line_width: float = 2.0,
    marker_size: float = 4.8,
) -> List[Line2D]:
    panel_metric_df = df[(df["panel"] == panel_name) & (df["metric"] == metric)].copy()
    if panel_metric_df.empty:
        raise ValueError(f"No data for panel={panel_name}, metric={metric}")

    legend_handles: List[Line2D] = []
    labels = ordered_groups(panel_metric_df, panel_name)

    # Plot reference first, then subgroups.
    for label in labels:
        gdf = panel_metric_df[panel_metric_df["subgroup_label"].astype(str) == label].copy()
        if gdf.empty:
            continue
        gdf = gdf.sort_values("task_order")
        color, ls, marker, is_ref = get_style(gdf, label)
        x, y, yerr = values_for_group(gdf)

        z = 2 if is_ref else 3
        alpha = 0.92 if is_ref else 1.0
        lw = line_width * (0.90 if is_ref else 1.00)
        ms = marker_size * (0.92 if is_ref else 1.00)

        ax.plot(
            x, y,
            linestyle=ls,
            color=color,
            marker=marker,
            markersize=ms,
            markerfacecolor="white" if is_ref else color,
            markeredgecolor=color,
            markeredgewidth=1.2,
            linewidth=lw,
            alpha=alpha,
            zorder=z,
        )

        if show_errorbar:
            # Only show error bar at Mean point by default.
            mean_idx = TASK_ORDER.index("Mean across t1–t5")
            if np.isfinite(y[mean_idx]) and np.isfinite(yerr[mean_idx]):
                ax.errorbar(
                    [x[mean_idx]], [y[mean_idx]], yerr=[yerr[mean_idx]],
                    fmt="none",
                    ecolor=color,
                    elinewidth=1.2,
                    capsize=2.8,
                    capthick=1.1,
                    alpha=0.90,
                    zorder=z + 1,
                )

        legend_handles.append(
            Line2D(
                [0], [0],
                color=color,
                linestyle=ls,
                marker=marker,
                markersize=ms,
                markerfacecolor="white" if is_ref else color,
                markeredgecolor=color,
                linewidth=lw,
                label=str(label),
            )
        )

    return legend_handles


def plot_main_figure(
    df: pd.DataFrame,
    out_dir: Path,
    prefix: str,
    dpi: int = 600,
    show_errorbar: bool = True,
    font_family: str = "Arial",
    fig_width: float = 14.2,
    fig_height: float = 7.2,
) -> List[Path]:
    configure_matplotlib(font_family=font_family)
    out_dir.mkdir(parents=True, exist_ok=True)

    fig, axes = plt.subplots(
        nrows=2,
        ncols=3,
        figsize=(fig_width, fig_height),
        sharex=True,
        sharey="row",
        constrained_layout=False,
    )

    for col, panel_name in enumerate(PANEL_ORDER):
        for row, metric in enumerate(METRIC_ORDER):
            ax = axes[row, col]
            handles = plot_single_axis(
                ax,
                df=df,
                panel_name=panel_name,
                metric=metric,
                show_errorbar=show_errorbar,
            )
            prettify_axis(ax, metric=metric, show_xlabel=(row == 1))

            if row == 0:
                # 小标题保留，但删除 a/b/c
                title = PANEL_TITLE.get(panel_name, panel_name)
                ax.set_title(title, loc="center", fontweight="bold", fontsize=12.5,pad=10)

                n_groups = max(1, len(handles))

                # Age 组别较多，保留两行；T6 强制一排显示
                if panel_name == "Age":
                    ncol = 3
                elif panel_name == "T6 disease mechanism":
                    ncol = n_groups
                else:
                    ncol = n_groups

                make_panel_legend(ax, handles, ncol=ncol)

            # 不再隐藏 b/c 的 y 轴数值
            ax.tick_params(axis="y", labelleft=True)

            # 如果只想左侧保留 y 轴标题，保留下面这句；
            # 如果你希望 b/c 也显示 Accuracy / Macro-F1，则注释掉这三行。
            if col != 0:
                ax.set_ylabel("")

    # A light global title. Comment out if you prefer no title in paper figures.
    # fig.suptitle(
    #     "Task-wise robustness across age, sex, and disease-mechanism subgroups",
    #     y=0.985,
    #     fontsize=13.5,
    #     fontweight="bold",
    # )

    # fig.text(
    #     0.5,
    #     0.015,
    #     "t1, CPET functional class; t2, exercise capacity; t3, exercise ECG interpretation; "
    #     "t4, ventilatory function; t5, heart-rate reserve. Mean denotes mean across t1–t5.",
    #     ha="center",
    #     va="bottom",
    #     fontsize=8.8,
    # )

    plt.subplots_adjust(
        left=0.065,
        right=0.985,
        top=0.875,
        bottom=0.115,
        wspace=0.18,
        hspace=0.18,
    )

    saved_paths: List[Path] = []
    for ext in ["png", "pdf", "svg", "tiff"]:
        path = out_dir / f"{prefix}.{ext}"
        if ext in {"png", "tiff"}:
            fig.savefig(path, dpi=dpi, bbox_inches="tight")
        else:
            fig.savefig(path, bbox_inches="tight")
        saved_paths.append(path)
        print(f"[Saved] {path}")

    plt.close(fig)
    return saved_paths


# =============================================================================
# 3. CLI
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot subgroup task-profile main figure for Result 1.7."
    )
    parser.add_argument(
        "--input",
        type=str,
        default=str(DEFAULT_INPUT),
        help="Input Excel generated by build_subgroup_task_profile_tables.py.",
    )
    parser.add_argument(
        "--sheet",
        type=str,
        default=DEFAULT_SHEET,
        help="Sheet name containing Fig_subgroup_task_profile_data.",
    )
    parser.add_argument(
        "--out_dir",
        type=str,
        default=str(DEFAULT_OUT_DIR),
        help="Output directory for figures.",
    )
    parser.add_argument(
        "--prefix",
        type=str,
        default=DEFAULT_PREFIX,
        help="Output figure prefix.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=600,
        help="DPI for PNG/TIFF outputs.",
    )
    parser.add_argument(
        "--font_family",
        type=str,
        default="Arial",
        help="Preferred font family. Falls back to DejaVu Sans if unavailable.",
    )
    parser.add_argument(
        "--no_errorbar",
        action="store_true",
        help="Disable error bars at the Mean across t1-t5 point.",
    )
    parser.add_argument(
        "--fig_width",
        type=float,
        default=14.2,
        help="Figure width in inches.",
    )
    parser.add_argument(
        "--fig_height",
        type=float,
        default=7.2,
        help="Figure height in inches.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    out_dir = Path(args.out_dir)

    print(f"[Input] {input_path}")
    print(f"[Sheet] {args.sheet}")

    df = load_profile_data(input_path, args.sheet)
    print(f"[Loaded] rows={len(df)}, panels={df['panel'].nunique()}, metrics={df['metric'].nunique()}")

    # Basic check: each panel should have Accuracy and Macro-F1.
    check = df.groupby(["panel", "metric"]).size().unstack(fill_value=0)
    print("[Panel x metric counts]")
    print(check)

    plot_main_figure(
        df=df,
        out_dir=out_dir,
        prefix=args.prefix,
        dpi=args.dpi,
        show_errorbar=not args.no_errorbar,
        font_family=args.font_family,
        fig_width=args.fig_width,
        fig_height=args.fig_height,
    )


if __name__ == "__main__":
    main()

