#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Plot main subgroup figure:
2 rows × 3 columns
Top row: Mean Accuracy across t1–t5
Bottom row: Mean Macro-F1 across t1–t5
Columns: Age / Sex / Disease-mechanism subgroup

Input:
    Excel sheet 'Fig_subgroup_main_mean_data'
    generated by build_subgroup_task_profile_tables.py
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List, Optional

import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.lines import Line2D


# =========================================================
# Default paths
# =========================================================
DEFAULT_INPUT = Path(
    r"xx_path"
)
DEFAULT_SHEET = "Fig_subgroup_main_mean_data"
DEFAULT_OUTDIR = Path(
    r"xx_path"
)


# =========================================================
# Panel / metric settings
# =========================================================
PANEL_ORDER = [
    "Age subgroup",
    "Sex subgroup",
    "Disease-mechanism subgroup",
]

METRIC_ORDER = [
    "Accuracy",
    "Macro-F1",
]

PANEL_TITLES = {
    "Age subgroup": "Age subgroup",
    "Sex subgroup": "Sex subgroup",
    "Disease-mechanism subgroup": "Disease-mechanism subgroup",
}

ROW_TITLES = {
    "Accuracy": "Mean Accuracy across t1–t5",
    "Macro-F1": "Mean Macro-F1 across t1–t5",
}

# 统一 y 轴范围（按你最终版式建议）
YLIMS = {
    "Accuracy": (0.78, 0.90),
    "Macro-F1": (0.68, 0.83),
}

# 如果 Excel 中没有颜色列，则使用 fallback
FALLBACK_COLORS = {
    # age
    "Age <40": "#B8D7F0",
    "Age 40–49": "#7FB3D5",
    "Age 50–59": "#4F81BD",
    "Age ≥60": "#1F4E79",
    # sex
    "Female": "#B07AA1",
    "Male": "#59A89C",
    # t6
    "CMP": "#2C7FB8",
    "HTx": "#7FC97F",
    "IHD": "#F28E2B",
    "PVD": "#C06CAB",
    # default
    "__default__": "#4C78A8",
}


# =========================================================
# Helpers
# =========================================================
def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """标准化列名，便于兼容不同 sheet 输出。"""
    rename_map = {}
    for c in df.columns:
        cc = str(c).strip()
        rename_map[c] = cc
    return df.rename(columns=rename_map)


def require_columns(df: pd.DataFrame, required: List[str]) -> None:
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(
            "输入 sheet 缺少必要列：\n"
            f"{missing}\n"
            "请检查 build_subgroup_task_profile_tables.py 输出的 "
            "'Fig_subgroup_main_mean_data' sheet。"
        )


def get_reference_value(sub: pd.DataFrame) -> Optional[float]:
    """
    优先读取 reference_value；
    如果没有，则尝试从 is_reference==True 的行的 mean 中获取。
    """
    if "reference_value" in sub.columns:
        vals = sub["reference_value"].dropna().unique().tolist()
        if vals:
            return float(vals[0])

    if "is_reference" in sub.columns:
        ref_rows = sub[sub["is_reference"].astype(str).str.lower().isin(["true", "1", "yes"])]
        if not ref_rows.empty and "mean" in ref_rows.columns:
            return float(ref_rows.iloc[0]["mean"])

    return None


def build_legend_handle_for_reference() -> List[Line2D]:
    return [
        Line2D(
            [0], [0],
            color="black",
            linestyle="--",
            linewidth=1.4,
            label="Full cohort",
        )
    ]


def get_color(row: pd.Series) -> str:
    if "plot_color" in row.index and pd.notna(row["plot_color"]) and str(row["plot_color"]).strip():
        return str(row["plot_color"]).strip()
    label = str(row["subgroup_label"]).strip()
    return FALLBACK_COLORS.get(label, FALLBACK_COLORS["__default__"])


def annotate_extremes(ax, xs: List[float], ys: List[float], labels: List[str], y_pad: float = 0.004) -> None:
    """只标最高值和最低值，避免图面拥挤。"""
    if len(xs) <= 1:
        return

    idx_max = max(range(len(ys)), key=lambda i: ys[i])
    idx_min = min(range(len(ys)), key=lambda i: ys[i])

    done = set()
    for idx, va, dy in [(idx_max, "bottom", y_pad), (idx_min, "top", -y_pad)]:
        if idx in done:
            continue
        done.add(idx)
        ax.text(
            xs[idx],
            ys[idx] + dy,
            labels[idx],
            ha="center",
            va=va,
            fontsize=8.5,
        )


# =========================================================
# Plot function
# =========================================================
def plot_main_figure(
    df: pd.DataFrame,
    out_dir: Path,
    dpi: int = 300,
    annotate_high_low: bool = False,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    plt.rcParams["font.family"] = "DejaVu Sans"
    plt.rcParams["axes.unicode_minus"] = False

    fig, axes = plt.subplots(
        nrows=2,
        ncols=3,
        figsize=(13.8, 7.2),
        sharey="row",
        constrained_layout=False,
    )

    for row_idx, metric in enumerate(METRIC_ORDER):
        for col_idx, panel in enumerate(PANEL_ORDER):
            ax = axes[row_idx, col_idx]

            sub = df[(df["metric"] == metric) & (df["panel"] == panel)].copy()
            if sub.empty:
                ax.set_visible(False)
                continue

            # 参考值（Full cohort）
            ref_val = get_reference_value(sub)

            # 去掉 reference 行，只画各 subgroup 点
            if "is_reference" in sub.columns:
                sub = sub[~sub["is_reference"].astype(str).str.lower().isin(["true", "1", "yes"])].copy()

            if sub.empty:
                ax.set_visible(False)
                continue

            # 排序
            if "subgroup_order" in sub.columns:
                sub = sub.sort_values(["subgroup_order", "subgroup_label"])
            else:
                sub = sub.sort_values(["subgroup_label"])

            subgroup_labels = sub["subgroup_label"].astype(str).tolist()
            yvals = sub["mean"].astype(float).tolist()
            yerr = sub["sd"].astype(float).tolist() if "sd" in sub.columns else [0.0] * len(sub)
            colors = [get_color(row) for _, row in sub.iterrows()]
            xs = list(range(len(subgroup_labels)))

            # 参考虚线
            if ref_val is not None:
                ax.axhline(
                    ref_val,
                    color="black",
                    linestyle="--",
                    linewidth=1.2,
                    alpha=0.95,
                    zorder=1,
                )

            # 误差线
            ax.errorbar(
                xs,
                yvals,
                yerr=yerr,
                fmt="none",
                ecolor="black",
                elinewidth=1.0,
                capsize=3,
                capthick=1.0,
                zorder=2,
            )

            # 点
            ax.scatter(
                xs,
                yvals,
                s=75,
                c=colors,
                edgecolors="black",
                linewidths=0.8,
                zorder=3,
            )

            # 轴设置
            ax.set_xticks(xs)
            ax.set_xticklabels(subgroup_labels, rotation=18, ha="right")
            ax.set_ylim(*YLIMS[metric])

            if col_idx == 0:
                ax.set_ylabel(metric, fontsize=11)

            if row_idx == 0:
                ax.set_title(PANEL_TITLES[panel], fontsize=12, pad=12, fontweight="bold")

            # 细节样式
            ax.grid(axis="y", linestyle=":", linewidth=0.8, alpha=0.55)
            ax.spines["top"].set_visible(False)
            ax.spines["right"].set_visible(False)
            ax.tick_params(axis="both", labelsize=10)

            # 行标题放在左侧图内部上方
            if col_idx == 0:
                ax.text(
                    -0.02,
                    1.06,
                    ROW_TITLES[metric],
                    transform=ax.transAxes,
                    ha="left",
                    va="bottom",
                    fontsize=11,
                    fontweight="bold",
                )

            # 只标最高值和最低值（可选）
            if annotate_high_low:
                annotate_extremes(ax, xs, yvals, subgroup_labels)

    # 下排统一 x label
    for ax in axes[1, :]:
        ax.set_xlabel("Subgroup", fontsize=11)

    # 上排不加 xlabel
    for ax in axes[0, :]:
        ax.set_xlabel("")

    # 图例：只放 Full cohort 虚线
    fig.legend(
        handles=build_legend_handle_for_reference(),
        loc="upper center",
        ncol=1,
        frameon=False,
        bbox_to_anchor=(0.5, 1.01),
        fontsize=10,
    )

    fig.tight_layout(rect=[0.03, 0.03, 0.99, 0.96], w_pad=2.0, h_pad=2.0)

    # 保存
    png_path = out_dir / "Fig_subgroup_main_mean.png"
    pdf_path = out_dir / "Fig_subgroup_main_mean.pdf"
    svg_path = out_dir / "Fig_subgroup_main_mean.svg"
    tiff_path = out_dir / "Fig_subgroup_main_mean.tiff"

    fig.savefig(png_path, dpi=dpi, bbox_inches="tight")
    fig.savefig(pdf_path, dpi=dpi, bbox_inches="tight")
    fig.savefig(svg_path, dpi=dpi, bbox_inches="tight")
    fig.savefig(tiff_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)

    print(f"[Saved] {png_path}")
    print(f"[Saved] {pdf_path}")
    print(f"[Saved] {svg_path}")
    print(f"[Saved] {tiff_path}")


# =========================================================
# Main
# =========================================================
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot main subgroup robustness figure (mean across t1–t5)."
    )
    parser.add_argument(
        "--input",
        type=str,
        default=str(DEFAULT_INPUT),
        help="Input Excel workbook path.",
    )
    parser.add_argument(
        "--sheet",
        type=str,
        default=DEFAULT_SHEET,
        help="Input sheet name.",
    )
    parser.add_argument(
        "--out_dir",
        type=str,
        default=str(DEFAULT_OUTDIR),
        help="Output directory for figure files.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="Figure dpi.",
    )
    parser.add_argument(
        "--annotate_high_low",
        action="store_true",
        help="Whether to annotate highest / lowest subgroup in each panel.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    input_path = Path(args.input)
    out_dir = Path(args.out_dir)

    if not input_path.exists():
        raise FileNotFoundError(f"输入文件不存在：{input_path}")

    df = pd.read_excel(input_path, sheet_name=args.sheet)
    df = normalize_columns(df)

    required_cols = [
        "panel",
        "metric",
        "subgroup_label",
        "mean",
        "sd",
    ]
    require_columns(df, required_cols)

    plot_main_figure(
        df=df,
        out_dir=out_dir,
        dpi=args.dpi,
        annotate_high_low=args.annotate_high_low,
    )


if __name__ == "__main__":
    main()
